// [getPos Object, 5000] execVM "turnOffLights.sqf";

params ["_position", "_radiusFromMarker"];

_nearLights = [
	"Building",
	"House",
	"House_Small",
	"Lamps_base_F",
	"Land_Airport_01_controlTower_F",
	"Land_Airport_01_terminal_F",
	"Land_Airport_02_controlTower_F",
	"Land_Airport_02_terminal_F",
	"Land_d_House_Big_01_V1_F",
	"Land_d_House_Small_01_V1_F",
	"Land_Flush_Light_green_F",
	"Land_Flush_Light_red_F",
	"Land_Flush_Light_white_F",
	"Land_Flush_Light_yellow_F",
	"Land_fs_feed_F",
	"Land_fs_roof_F",
	"Land_fs_sign_F",
	"Land_FuelStation_01_pump_F",
	"Land_FuelStation_01_pump_malevil_F",
	"Land_FuelStation_01_shop_F",
	"Land_FuelStation_02_big_F",
	"Land_FuelStation_02_pump_F",
	"Land_FuelStation_02_roof_F",
	"Land_FuelStation_02_roof_malevil_F",
	"Land_FuelStation_02_shop_F",
	"Land_FuelStation_Build_F",
	"Land_FuelStation_Feed_F",
	"Land_FuelStation_Shed_F",
	"Land_i_House_Big_01_V1_F",
	"Land_i_House_Big_02_V1_F",
	"Land_i_House_Small_01_V1_F",
	"Land_i_House_Small_02_V1_F",
	"Land_LampAirport_F",
	"Land_LampAirport_off_F",
	"Land_LampCeiling_F",
	"Land_LampDecor_F",
	"Land_LampGarden_F",
	"Land_LampHalogen_F",
	"Land_LampHalogen_off_F",
	"Land_LampHarbour_F",
	"Land_LampIndustrial_F",
	"Land_LampShabby_F",
	"Land_LampSolar_F",
	"Land_LampSolar_off_F",
	"Land_LampStreet_02_double_F",
	"Land_LampStreet_02_F",
	"Land_LampStreet_02_quad_F",
	"Land_LampStreet_02_small_F",
	"Land_LampStreet_02_triple_F",
	"Land_LampStreet_F",
	"Land_LampStreet_small_F",
	"Land_LampTower_F",
	"Land_LampWall_F",
	"Land_NavigLight",
	"Land_NavigLight_1_F",
	"Land_NavigLight_2_F",
	"Land_NavigLight_3_F",
	"Land_NavigLight_4_F",
	"Land_PortableLight_01_double_F",
	"Land_PortableLight_01_single_F",
	"Land_PortableLight_double_F",
	"Land_PortableLight_single_F",
	"Land_PowerPoleConcrete_F",
	"Land_PowerPoleConcrete_L_F",
	"Land_PowerPoleWooden_F",
	"Land_PowerPoleWooden_L_F",
	"Land_PowerStation_F",
	"Land_runway_edgelight",
	"Land_runway_edgelight_blue_F",
	"Land_runway_edgelight_red_F",
	"Land_runway_edgelight_white_F",
	"Land_Runway_PAPI",
	"Land_Runway_PAPI_2",
	"Land_Runway_PAPI_3",
	"Land_Runway_PAPI_4",
	"Land_RunwayLight",
	"Land_RunwayLight_01_F",
	"Land_StreetLamp_F",
	"Land_TaxiwayLight",
	"Land_TaxiwayLight_01_F",
	"Land_u_House_Big_01_V1_F",
	"Land_u_House_Small_01_V1_F",
	"PowerLines_base_F",
	"PowerLines_Small_base_F"
];

{
	private _lamps = _position nearObjects [_x, _radiusFromMarker];
	{
		hideObjectGlobal _x;
	} forEach _lamps;
} forEach _nearLights;