name: Arma 3 CI - SQF Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run SQF Linter
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            --entrypoint sqflint \
            acemod/sqflint \
            -d /workspace > lint.log 2>&1
          echo "SQFLint output:"
          cat lint.log
          if grep -q "error:" lint.log; then
            echo "Errors found in SQF linting! Failing the workflow."
            exit 1
          fi